project:
  type: website
  output-dir: docs

website:
  title: "DarrenQuartoGithubWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - about.qmd
      - section: "Quarto"
        contents:
          - QuartoInstallNotes.qmd
          - UsingGithubPagesWithQuarto.qmd
          - AddPagesAndNavigation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



